name: pages
on: [push, pull_request]

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
          npm ci
          gem install bundler
          bundle install --jobs 4 --retry 3
          ./rake

      - name: Deploy
        uses: ferrous-systems/shared-github-actions/github-pages@main
        with:
          path: target/
          token: ${{ secrets.GITHUB_TOKEN  }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
